name: Convert MD to HTML and Update Blog and create Github Page

permissions:
  contents: write

on:
  push:
    branches:
      - main
   
jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installa Pandoc
      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: permission
        run: chmod +x convert.sh 

      - name: run script convert and add post
        run: ./convert.sh
        
      # Esegui git pull prima del commit e push
      - name: Pull latest changes from remote
        run: |
          git pull origin main

      # Fai il commit e push dei cambiamenti
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public/blog.html
          git diff --staged --quiet || git commit -m "Aggiornato blog.html con nuovi post"
          git push || echo "No changes to push"
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Crea la GitHub Page (pubblica su gh-pages)
      - name: Create GitHub Pages
        run: |
          # Checkout della branch gh-pages, creando se non esiste
          git checkout -B gh-pages

          # Copia i file generati nella directory di root
          cp -r public/* .

          # Aggiungi i cambiamenti
          git add .
          git commit -m "Update GitHub Pages with new posts"

          # Push alla branch gh-pages
          git push --force origin gh-pages